### 一. 回调
见test4.test.js, 有个done函数作为参数,变成异步测试案例.运行案例发现,如果没有执行done,默认5秒钟超时后会测试失败.执行done函数,修改时间,当小于5秒没有返回,也会失败.
```
test('the data is peanut butter', done => {
  function callback(data) {
    expect(data).toBe('peanut butter');
    done(); // 异步要执行done才会通过测试
  }

  fetchData(callback);
});
```

### 二. Promise
promise版就更加简单了, 运行案例`jest -t 'the data is peanut butter Promise'`,注意要加return,不然案例会在.then()提前结束
```
test('the data is peanut butter Promise', () => {
  return fetchDataPromise().then(data => {
    expect(data).toBe('peanut butter');
  });
});
```
以下要测reject, expect.assertions(1)要求断言执行一次,不然resolve也会导致测试通过. 运行案例, 删掉或者修改断言次数试试
```
test('the fetch fails with an error', () => {
  expect.assertions(1);
  return fetchDataPromiseFalse().catch(e => expect(e).toMatch('error'));
});
```
还支持.resolves和.rejects写法
```
test('the data is peanut butter', () => {
  return expect(fetchDataPromise()).resolves.toBe('peanut butter');
});

test('the fetch fails with an error', () => {
  return expect(fetchDataPromiseFalse()).rejects.toMatch('error');
});
```

### 三. Async await
只是peomise的语法糖
```
test('the data is peanut butter', async () => {
  expect.assertions(1);
  const data = await fetchData();
  expect(data).toBe('peanut butter');
});

test('the fetch fails with an error', async () => {
  expect.assertions(1);
  try {
    await fetchData();
  } catch (e) {
    expect(e).toMatch('error');
  }
});
// Of course, you can combine async and await with .resolves or .rejects.

test('the data is peanut butter', async () => {
  await expect(fetchData()).resolves.toBe('peanut butter');
});

test('the fetch fails with an error', async () => {
  await expect(fetchData()).rejects.toThrow('error');
});
在这些情况下，async 和 await 仅仅只是语法糖，其本身的逻辑与上述使用 Promise 的示例等效。
```
